[project]
name = "python-template"
version = "0.1.0"
gunicorn = "20.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "flask>=3.1.1",
    "numpy>=2.3.2",
    "parse>=1.20.2",
    "python-dotenv>=1.1.1",
]
